CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR(50) NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    display_name VARCHAR(100) NOT NULL,
    email VARCHAR(254),
    role VARCHAR(20) NOT NULL DEFAULT 'OPERATOR',
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    last_login_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT ck_users_username_not_blank CHECK (BTRIM(username) <> ''),
    CONSTRAINT ck_users_display_name_not_blank CHECK (BTRIM(display_name) <> ''),
    CONSTRAINT ck_users_email_not_blank CHECK (email IS NULL OR BTRIM(email) <> ''),
    CONSTRAINT ck_users_role CHECK (role IN ('ADMIN', 'OPERATOR')),
    CONSTRAINT ck_users_status CHECK (status IN ('ACTIVE', 'DISABLED'))
);

CREATE UNIQUE INDEX uk_users_username_lower
    ON users (LOWER(username));

CREATE UNIQUE INDEX uk_users_email_lower
    ON users (LOWER(email))
    WHERE email IS NOT NULL;

CREATE TABLE advertiser_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_advertiser_categories PRIMARY KEY (id),
    CONSTRAINT ck_advertiser_categories_name_not_blank CHECK (BTRIM(name) <> ''),
    CONSTRAINT ck_advertiser_categories_status CHECK (status IN ('ACTIVE', 'DISABLED')),
    CONSTRAINT ck_advertiser_categories_sort_order CHECK (sort_order >= 0)
);

CREATE UNIQUE INDEX uk_advertiser_categories_name_lower
    ON advertiser_categories (LOWER(name));

CREATE INDEX idx_advertiser_categories_status_sort_order
    ON advertiser_categories (status, sort_order);

CREATE TABLE advertisers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(200) NOT NULL,
    registration_no VARCHAR(64),
    category_id BIGINT,
    owner_user_id BIGINT,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    website VARCHAR(255),
    address VARCHAR(500),
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_advertisers PRIMARY KEY (id),
    CONSTRAINT ck_advertisers_name_not_blank CHECK (BTRIM(name) <> ''),
    CONSTRAINT ck_advertisers_registration_no_not_blank
        CHECK (registration_no IS NULL OR BTRIM(registration_no) <> ''),
    CONSTRAINT ck_advertisers_status CHECK (status IN ('ACTIVE', 'DISABLED')),
    CONSTRAINT fk_advertisers_category
        FOREIGN KEY (category_id)
        REFERENCES advertiser_categories (id)
        ON DELETE SET NULL,
    CONSTRAINT fk_advertisers_owner_user
        FOREIGN KEY (owner_user_id)
        REFERENCES users (id)
        ON DELETE SET NULL
);

CREATE UNIQUE INDEX uk_advertisers_name_lower
    ON advertisers (LOWER(name));

CREATE UNIQUE INDEX uk_advertisers_registration_no
    ON advertisers (registration_no)
    WHERE registration_no IS NOT NULL;

CREATE INDEX idx_advertisers_category_id
    ON advertisers (category_id);

CREATE INDEX idx_advertisers_owner_user_id
    ON advertisers (owner_user_id);

CREATE INDEX idx_advertisers_status
    ON advertisers (status);
