CREATE TABLE advertising_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code VARCHAR(30) NOT NULL,
    name VARCHAR(100) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_advertising_types PRIMARY KEY (id),
    CONSTRAINT ck_advertising_types_code_not_blank CHECK (BTRIM(code) <> ''),
    CONSTRAINT ck_advertising_types_name_not_blank CHECK (BTRIM(name) <> ''),
    CONSTRAINT ck_advertising_types_status CHECK (status IN ('ACTIVE', 'DISABLED'))
);

CREATE UNIQUE INDEX uk_advertising_types_code_lower
    ON advertising_types (LOWER(code));

INSERT INTO advertising_types (code, name)
VALUES
    ('SEARCH', '搜索广告'),
    ('DISPLAY', '展示广告'),
    ('VIDEO', '视频广告'),
    ('SOCIAL', '社交媒体广告');

CREATE TABLE advertising_delivery_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    external_record_no VARCHAR(64) NOT NULL,
    advertiser_id BIGINT NOT NULL,
    advertising_type_id BIGINT NOT NULL,
    record_date DATE NOT NULL,
    impressions BIGINT NOT NULL DEFAULT 0,
    clicks BIGINT NOT NULL DEFAULT 0,
    conversions BIGINT NOT NULL DEFAULT 0,
    spend NUMERIC(19, 2) NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_advertising_delivery_records PRIMARY KEY (id),
    CONSTRAINT ck_advertising_delivery_external_no_not_blank
        CHECK (BTRIM(external_record_no) <> ''),
    CONSTRAINT ck_advertising_delivery_impressions
        CHECK (impressions >= 0),
    CONSTRAINT ck_advertising_delivery_clicks
        CHECK (clicks >= 0 AND clicks <= impressions),
    CONSTRAINT ck_advertising_delivery_conversions
        CHECK (conversions >= 0 AND conversions <= clicks),
    CONSTRAINT ck_advertising_delivery_spend
        CHECK (spend >= 0),
    CONSTRAINT fk_advertising_delivery_advertiser
        FOREIGN KEY (advertiser_id)
        REFERENCES advertisers (id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_advertising_delivery_type
        FOREIGN KEY (advertising_type_id)
        REFERENCES advertising_types (id)
        ON DELETE RESTRICT
);

CREATE UNIQUE INDEX uk_advertising_delivery_external_record_no
    ON advertising_delivery_records (external_record_no);

CREATE INDEX idx_advertising_delivery_record_date
    ON advertising_delivery_records (record_date);

CREATE INDEX idx_advertising_delivery_advertiser_date
    ON advertising_delivery_records (advertiser_id, record_date);

CREATE INDEX idx_advertising_delivery_type_date
    ON advertising_delivery_records (advertising_type_id, record_date);
