CREATE TABLE advertiser_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    advertiser_id BIGINT NOT NULL,
    balance NUMERIC(19, 2) NOT NULL DEFAULT 0.00,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_advertiser_accounts PRIMARY KEY (id),
    CONSTRAINT ck_advertiser_accounts_balance CHECK (balance >= 0),
    CONSTRAINT fk_advertiser_accounts_advertiser
        FOREIGN KEY (advertiser_id)
        REFERENCES advertisers (id)
        ON DELETE RESTRICT
);

CREATE UNIQUE INDEX uk_advertiser_accounts_advertiser_id
    ON advertiser_accounts (advertiser_id);

INSERT INTO advertiser_accounts (advertiser_id)
SELECT id
FROM advertisers;

CREATE TABLE advertiser_account_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    advertiser_account_id BIGINT NOT NULL,
    business_no VARCHAR(64) NOT NULL,
    transaction_type VARCHAR(30) NOT NULL,
    amount NUMERIC(19, 2) NOT NULL,
    balance_after NUMERIC(19, 2) NOT NULL,
    advertising_delivery_record_id BIGINT,
    remark VARCHAR(500),
    created_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_advertiser_account_transactions PRIMARY KEY (id),
    CONSTRAINT ck_account_transactions_business_no_not_blank
        CHECK (BTRIM(business_no) <> ''),
    CONSTRAINT ck_account_transactions_type
        CHECK (transaction_type IN ('RECHARGE', 'CONSUMPTION')),
    CONSTRAINT ck_account_transactions_amount
        CHECK (amount > 0),
    CONSTRAINT ck_account_transactions_balance_after
        CHECK (balance_after >= 0),
    CONSTRAINT fk_account_transactions_account
        FOREIGN KEY (advertiser_account_id)
        REFERENCES advertiser_accounts (id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_account_transactions_delivery_record
        FOREIGN KEY (advertising_delivery_record_id)
        REFERENCES advertising_delivery_records (id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_account_transactions_created_by
        FOREIGN KEY (created_by)
        REFERENCES users (id)
        ON DELETE SET NULL
);

CREATE UNIQUE INDEX uk_account_transactions_business_no
    ON advertiser_account_transactions (business_no);

CREATE INDEX idx_account_transactions_account_created
    ON advertiser_account_transactions (advertiser_account_id, created_at DESC);

CREATE INDEX idx_account_transactions_delivery_record
    ON advertiser_account_transactions (advertising_delivery_record_id)
    WHERE advertising_delivery_record_id IS NOT NULL;
