CREATE TABLE recharge_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    order_no VARCHAR(64) NOT NULL,
    advertiser_account_id BIGINT NOT NULL,
    amount NUMERIC(19, 2) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    provider_transaction_no VARCHAR(100),
    paid_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_recharge_orders PRIMARY KEY (id),
    CONSTRAINT ck_recharge_orders_order_no_not_blank
        CHECK (BTRIM(order_no) <> ''),
    CONSTRAINT ck_recharge_orders_amount
        CHECK (amount > 0),
    CONSTRAINT ck_recharge_orders_status
        CHECK (status IN ('PENDING', 'SUCCESS', 'FAILED', 'CLOSED')),
    CONSTRAINT ck_recharge_orders_provider_no_not_blank
        CHECK (provider_transaction_no IS NULL OR BTRIM(provider_transaction_no) <> ''),
    CONSTRAINT ck_recharge_orders_paid_at
        CHECK ((status = 'SUCCESS' AND paid_at IS NOT NULL)
            OR (status <> 'SUCCESS' AND paid_at IS NULL)),
    CONSTRAINT fk_recharge_orders_account
        FOREIGN KEY (advertiser_account_id)
        REFERENCES advertiser_accounts (id)
        ON DELETE RESTRICT
);

CREATE UNIQUE INDEX uk_recharge_orders_order_no
    ON recharge_orders (order_no);

CREATE UNIQUE INDEX uk_recharge_orders_provider_transaction_no
    ON recharge_orders (provider_transaction_no)
    WHERE provider_transaction_no IS NOT NULL;

CREATE INDEX idx_recharge_orders_account_created
    ON recharge_orders (advertiser_account_id, created_at DESC);

CREATE INDEX idx_recharge_orders_status_created
    ON recharge_orders (status, created_at DESC);

CREATE TABLE recharge_payment_callbacks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    provider_event_id VARCHAR(100) NOT NULL,
    recharge_order_id BIGINT NOT NULL,
    callback_status VARCHAR(20) NOT NULL DEFAULT 'RECEIVED',
    payload_hash VARCHAR(64) NOT NULL,
    failure_reason VARCHAR(500),
    received_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    processed_at TIMESTAMPTZ,
    CONSTRAINT pk_recharge_payment_callbacks PRIMARY KEY (id),
    CONSTRAINT ck_recharge_callbacks_event_id_not_blank
        CHECK (BTRIM(provider_event_id) <> ''),
    CONSTRAINT ck_recharge_callbacks_status
        CHECK (callback_status IN ('RECEIVED', 'PROCESSED', 'DUPLICATE', 'REJECTED')),
    CONSTRAINT ck_recharge_callbacks_payload_hash
        CHECK (CHAR_LENGTH(payload_hash) = 64),
    CONSTRAINT ck_recharge_callbacks_processed_at
        CHECK (callback_status = 'RECEIVED' OR processed_at IS NOT NULL),
    CONSTRAINT fk_recharge_callbacks_order
        FOREIGN KEY (recharge_order_id)
        REFERENCES recharge_orders (id)
        ON DELETE RESTRICT
);

CREATE UNIQUE INDEX uk_recharge_callbacks_provider_event_id
    ON recharge_payment_callbacks (provider_event_id);

CREATE INDEX idx_recharge_callbacks_order_received
    ON recharge_payment_callbacks (recharge_order_id, received_at DESC);

ALTER TABLE advertiser_account_transactions
    ADD COLUMN recharge_order_id BIGINT,
    ADD CONSTRAINT fk_account_transactions_recharge_order
        FOREIGN KEY (recharge_order_id)
        REFERENCES recharge_orders (id)
        ON DELETE RESTRICT;

CREATE UNIQUE INDEX uk_account_transactions_recharge_order_id
    ON advertiser_account_transactions (recharge_order_id)
    WHERE recharge_order_id IS NOT NULL;
